language: python
sudo: false
cache: pip
python: 3.6
dist: focal
jobs:
  include:
    - os: linux
      arch: arm64
      env:
        - BLIS_ARCH="cortexa57"
    - os: linux
      arch: ppc64le
      env:
        - BLIS_ARCH="power9"
install:
  - "python -m pip install -U pip setuptools"
  - "pip install cython numpy"
  - "pip install --no-build-isolation cymem murmurhash"
  - "pip install --no-build-isolation preshed"
  - "pip install --no-build-isolation thinc --pre"
  - "pip install --no-build-isolation -r requirements.txt"
  - "pip install --no-deps -v -e ."
script:
  - "cat /proc/cpuinfo | grep flags | head -n 1"
  - "python -m pytest --tb=native spacy"
branches:
  except:
    - spacy.io
    - nightly.spacy.io
notifications:
  slack:
    secure: F8GvqnweSdzImuLL64TpfG0i5rYl89liyr9tmFVsHl4c0DNiDuGhZivUz0M1broS8svE3OPOllLfQbACG/4KxD890qfF9MoHzvRDlp7U+RtwMV/YAkYn8MGWjPIbRbX0HpGdY7O2Rc9Qy4Kk0T8ZgiqXYIqAz2Eva9/9BlSmsJQ=
  email: false
